"""Shared constants for vOrchestrate core modules."""

STATE_HBM_FULL_PRECISION = 0
STATE_HBM_LOW_BIT = 1
STATE_HBM_COMPRESSED = 2
STATE_HOST_DRAM = 3
STATE_NVME = 4
STATE_IN_FLIGHT = 5
STATE_RECOMPUTABLE = 6

HBM_RESIDENT_STATES = {
    STATE_HBM_FULL_PRECISION,
    STATE_HBM_LOW_BIT,
    STATE_HBM_COMPRESSED,
}

ALL_WEIGHT_STATES = {
    STATE_HBM_FULL_PRECISION,
    STATE_HBM_LOW_BIT,
    STATE_HBM_COMPRESSED,
    STATE_HOST_DRAM,
    STATE_NVME,
    STATE_IN_FLIGHT,
    STATE_RECOMPUTABLE,
}
